### ISSUE TITLE
Procedure

### ISSUE THREAD

**Issue by vickyskarthik** [aws-samples/aws-serverless-telepresence-robot#3]
Can you post a link for step by step procedure to implement this project?

Thanks in advance?

**Comment by virgilvox** [comment]
Hi! The full instructions are published as two blog posts.

Part 1 https://aws.amazon.com/blogs/compute/building-a-raspberry-pi-telepresence-robot-using-serverless-part-1/
Part 2 https://aws.amazon.com/blogs/compute/building-a-raspberry-pi-telepresence-robot-using-serverless-part-2/
